site:
  title: Dialog
  start_page: dialog::index.adoc
content:
  sources:
    start_path: manual
  - url: https://github.com/Dialog-IF/dialog.git
    branches: ['hls/20250120-antora']
  - url: https://github.com/hlship/dialog.git
    branches: ~
    tags: release-*
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui-overrides 
asciidoc: 
  extensions:
    - lib/macros.js
antora:
  extensions:
    - '@antora/lunr-extension'
